#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

import logging
import os.path
import shutil
import sys

# Set up the logging early on in the process.
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))

import ant
import util

instagram_version = util.get_instagram_version()
options = ['-Dbase.version=%s' % instagram_version, '-Dversion=%s' % instagram_version]

ant.clean()
ant.build(options)
ant.artifacts(options)
artifact_file = os.path.join(util.PROJECT_ROOT,
                             'build/apache-cassandra-%s-bin.tar.gz' % instagram_version)
rpm_file = util.rpmbuild(artifact_file, instagram_version)
shutil.copy(rpm_file, os.path.join(util.PROJECT_ROOT, 'build/cassandra.rpm'))
