#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

import json
import logging
import optparse
import os.path
import subprocess
import sys

# Set up the logging early on in the process.
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), './lib'))

import ant
import util

parser = optparse.OptionParser(usage='usage: %prog [options] test_name',
                               description='Run Cassandra tests')
parser.add_option('-b', '--build', action='store_true', default=False, help='Run build step first')
parser.add_option('-l', '--list', action='store_true', default=False, help='List available test')
parser.add_option('-a', '--all', action='store_true', default=False, help='Run all test')
parser.add_option('-j', '--json', action='store_true', default=False, help='Print output as Json')

options, args = parser.parse_args(sys.argv[1:])

if options.list:
    tests = ant.list_unit_tests()
    if options.json:
        print(json.dumps(tests))
    else:
        for test in tests:
            print(test)
    sys.exit(0)

if not options.all:
    if len(args) == 0:
        logging.error('Need to specifiy a test name.')
        sys.exit(1)

    if options.build:
        ant.build()

    ant.run_test(args[0])
    sys.exit(0)

test_summary = os.path.join(util.PROJECT_ROOT, 'build/test/TESTS-TestSuites.xml')

if os.path.isfile(test_summary):
    os.remove(test_summary)

try:
    ant.run_all_test()
except subprocess.CalledProcessError:
    # If the test summary is generated, suppress the error so that legocastle could
    # upload the test report.
    if not os.path.isfile(test_summary):
        raise
