#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

import os.path
import sys

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), './lib'))
import util
import junitreport

test_summary = os.path.join(util.PROJECT_ROOT, 'build/test/TESTS-TestSuites.xml')

if not os.path.isfile(test_summary):
    print("Tests haven't run yet")
    sys.exit(0)

failures = junitreport.failures(test_summary)

if len(failures) == 0:
    print('All test passed, have a nice day :-)')
    sys.exit(0)

print('\n>>>>>>>>>>> %i TESTS FAILED <<<<<<<<<<<\n' % len(failures))
print('```')
for i, failure in enumerate(failures):
    print("%d) %s" % (i+1, failure.testname))
    print(failure.error)
print('```')
